### ISSUE TITLE
Add new side bar for OUTQ report management.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#506] opened 2022-02-04 18:19 UTC
**Is your feature request related to a problem? Please describe.**
> Allow user to manage output reports from a tree view for things like copying to PDF or TXT, deleting (for now).

**Describe the solution you'd like**
> using this SQL to list SPLFs for CODE_USER.
<code>
     select SPOOLED_FILE_NAME
       ,JOB_NAME
       ,CREATE_TIMESTAMP
       ,FILE_NUMBER
       ,SYSTEM
       ,USER_NAME
       ,USER_DATA
       ,STATUS
       ,TOTAL_PAGES
       ,OUTPUT_QUEUE_NAME
       ,OUTPUT_QUEUE_LIBRARY_NAME
       ,SIZE
       ,COPIES
       ,FORM_TYPE
       ,DEVICE_TYPE
       ,OUTPUT_PRIORITY
    from QSYS2.OUTPUT_QUEUE_ENTRIES_BASIC
    where USER_NAME = CODE_USER
    order by CREATE_TIMESTAMP desc
    --  limit 15 offset 22 -- Use if UI tools allow for paging or expanding results.
</code>

> You might consider using the view that the SQL results appear in but that would mean you need to activate abilities to select the entry to do actions on an individual or multiple lines.   
> You might consider an all action like delete all.

**Comment by worksofliam** [comment] 2022-02-04 18:42
Duplicate of #58. I have reopened that and you should put your notes there.

**Closed** 2022-02-04 18:42 UTC
Labels: idea
