### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by rpxr400** [halcyon-tech/vscode-ibmi#1498] opened 2023-08-22 18:50 UTC
Tryin to connect to our Dev box and getting the error in subject line.
Initial error window is:

Not connected to (systemname)! No response from server
Source: Code for IBMi

When I look at Runtime Status of Code for IBMi, I see "Cannot read properties of undefined (reading 'name')" errors.
Activation event: onStartupFinished

Port 22 is open.

I can connect to our production box fine.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.1.0|
|Visual Studio Code version|1.81.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by worksofliam** [comment] 2023-08-22 18:54
Can you connect through a regular SSH client? For example, `ssh` from most shells, or putty, etc?

**Comment by rpxr400** [comment] 2023-08-22 19:43
I'm not familiar with this. I'll do some research.

**Comment by worksofliam** [comment] 2023-08-23 03:19
@rpxr400 the next step is to find out if the issue is due to SSH or due to Code for IBM i.

This error you're seeing is always shown and isn't unique to you, so I suspect some ssh issues.

Let us know when you manage to connect outside of Code for IBM i, and when you can, ensure your connection settings are correct.

**Comment by vuxat** [comment] 2023-08-23 11:58
Hi,

I have the same issue after Update to the latest version of VS Code (or the Plugin).
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/14197506/a57c9e44-d97f-4a90-8087-35c5d5f8e959)
And on a second machine:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/14197506/e8a497a8-4c69-40be-a205-08148b41a725)

ssh connection works perfectly.
When I add a new connection in the Plugin, and name it like Server 2 (because the name is already taken (so it can read it somehow), and connect immediately instead of just save&exit, it connects and I can work like always. It does not show up and on the next try "Server 2" is already taken.

Best regards,
Stefan

**Comment by worksofliam** [comment] 2023-08-23 13:28
@vuxat what language is your vscode instance configured to use? Looks like it could be related to locales?

**Comment by vuxat** [comment] 2023-08-23 13:47
> @vuxat what language is your vscode instance configured to use? Looks like it could be related to locales.

 @worksofliam my VSCode editors either run with english or german settings. de_AT.UTF8 maybe in the background?

**Comment by worksofliam** [comment] 2023-08-23 14:36
Look what I found! 
![Uploading image.png…]()

**Comment by vuxat** [comment] 2023-08-23 14:45
@worksofliam thank you!

**Comment by worksofliam** [comment] 2023-08-23 14:45
@vuxat Waiting for the attached PR above to be merged and then we can create a release :)

**Closed** 2023-08-23 14:49 UTC
Labels: info-needed

**Comment by worksofliam** [comment] 2023-08-23 14:57
@vuxat 2.1.1 is released with a fix. Thanks!
