### ISSUE TITLE
Open request when a file is locked does nothing.

### ISSUE THREAD

**Issue by ChrisHird** [halcyon-tech/vscode-ibmi#323] opened 2021-09-23 20:44 UTC
The request to open a file does not report any errors or allow open of a file in read only mode when it is locked by another user.

Tested by opening a file in RDi and then tried to open the same file in VS Code.

The file should be opened in read only mode and marked as such or if that is not possible send a notification that the file is locked and cannot be opened back to the IDE space.

**Comment by SJLennon** [comment] 2021-09-23 21:19
Actually, I does give a message but not immediately. It looks like the copy  fails when it times out.  I have ASTATE.RPGLE open in SEU and tried to open it in Code for IBM i.  After about 30 seconds I got this message:
![image](https://user-images.githubusercontent.com/67484051/134584826-b331f234-5522-4ca8-8b85-9faa8f75182a.png)

**Comment by ChrisHird** [comment] 2021-09-23 21:30
Ok so it’s the standard time out, I did not have output view opened which is why I never saw anything. Can the output be pushed up to a notification?

Sent from my iPhone
________________________________

**Comment by SJLennon** [comment] 2021-09-23 21:36
The OUTPUT view open is not a requirement.  I just had it open to see what was happening.
![image](https://user-images.githubusercontent.com/67484051/134587452-db027e4f-edb0-455a-8769-c895988fbf77.png)

**Comment by SJLennon** [comment] 2021-09-23 21:42
I tried changing the wait time for the file and also allocating the member *EXCLRD but it made no difference to the CPYTOSTMF.

**Comment by ChrisHird** [comment] 2021-09-23 21:54
The only way to get over the delay is to change the job that the request runs under to reduce the Default Wait Time. I don’t think that affects anything. I did not see any notifications about the file not being able to be read in any form, I only mentioned the fact that I did not have the output view open because I thought that was where you saw the lock failure being reported?

If there should be a notification somewhere I do not see it? Maybe that’s the only problem here?

Chris…

**Comment by SJLennon** [comment] 2021-09-23 22:00
So far I've always got the "Object in use" notification, down at the bottom right.  Maybe it goes automatically goes away eventually, but in testing today I haven't experience that.
Changing the wait time in the SSH job is something Liam would have to comment on. I agree it would be nice if it came back immediately, but it may not be practical.

**Comment by ChrisHird** [comment] 2021-09-23 22:01
Just checked again, the notification is returned as mentioned at the bottom of the screen  Maybe the only way to change this is to set the default wait time for the job as it loads down to 1 second or something CHGJOB DFTWAIT(1)
Or have the job run under a different job description that sets it to one? I do not know how the job is run between the IBM I and the IDE so not sure of the best way to achieve this.

Chris…

**Comment by worksofliam** [comment] 2021-09-23 22:03
I would say this is a duplicate of #217. Will likely close this one.

We currently have no way of locking or unlocking members.

**Closed** 2021-09-23 22:03 UTC

**Comment by worksofliam** [comment] 2021-09-23 22:07
@SJLennon Thanks for all your help here!!
