### ISSUE TITLE
Strange character

### ISSUE THREAD

**Issue by robycatta** [halcyon-tech/vscode-ibmi#661] opened 2022-04-30 21:46 UTC
First of all I work on a Macbook Air M1.
While using TN5250 within VisualStudio Code, it happens in an apparently random way, that using the arrows on the keyboard "strange" characters appear (eg: [A [C [C [B). What can it be caused by?

Roberto

* QCCSID: 65535
* Features enabled:
   * git: false
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: false

**Comment by worksofliam** [comment] 2022-05-03 12:55
Dupe of #662.

**Closed by worksofliam** 2022-05-03 12:55 UTC
