### ISSUE TITLE
Tab problem empty

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#581] opened 2022-03-08 11:52 UTC
Hi, 

from some days the problem tab doesn't give me compilation error.

In the tab IBM i Output the last error I see is this:
TypeError: Cannot read property 'groups' of null

And I have this notification:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/9719313/157232869-afa53699-adc5-4e00-8eec-8cb692008e58.png">

Code for IBM i
v1.2.2

IBM i 
V7R4 (but still compiling to previous)

Visual studio code version:
1.65.0

Let me know if you need more details.

**Comment by worksofliam** [comment] 2022-03-08 13:05
Fix incoming, but closing since a dupe of #580.

**Closed by worksofliam** 2022-03-08 13:05 UTC

**Comment by pabloto** [comment] 2022-03-08 13:15
@worksofliam  Many thanks!!!

**Comment by worksofliam** [comment] 2022-03-08 13:16
@pabloto it's out!

**Comment by pabloto** [comment] 2022-03-08 15:26
Perfect. Thanks
