### ISSUE TITLE
SQL inline comments and Run query don't mix

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#622] opened 2022-04-11 22:10 UTC
**Describe the bug**
I use inline SQL comments A LOT.  I use it to deactivate sections of the query, like removing a result column, removing a join line, insert CTE test lines, etc.  However, it appears the parser for Code for IBM i does not correctly recognize these comments.  
Inline comments are two dashes and a space.   It's the default comment for VS Code SQL language type shortcut Ctrl+/.   

I noticed today that one of my CTE test lines (a line that ends with a semi colon but is in the commented state) will cause the statement to be parsed only to that point. 

**To Reproduce**
Run this query.  

```
with t1 as (select SYSTEM_TABLE_SCHEMA ,SYSTEM_TABLE_NAME  ,SYSTEM_TABLE_MEMBER from QSYS2.SYSPARTITIONSTAT)
-- select * from T1  where TABLE_SCHEMA = 'D1WFIQUAL' and TABLE_NAME like 'KRNMDA%';
select * from T1  where TABLE_SCHEMA = 'D1WFIQUAL' and TABLE_NAME like 'KRNMDA%';
```

**Expected behavior**
I expect comments to be excluded from the run query but I understand that is a bit harder than it sounds.  

**Environment (please complete the following information):**
 - Extension version 1.2.6
 - IBM i OS version 7.3

**Comment by worksofliam** [comment] 2022-04-14 15:58
Someone actually found this issue before and ignored it.

This is a bug with the SQL processor on the system and not so much a bug with the extension. I can parse it and remove comments perhaps.

**Comment by m-tyler** [comment] 2022-04-14 16:13
Yep, my apologies.  I just tried it through 5250 QSH and I get the same errors.  

If its possible to remove those comments that would be great as even wrapping comments /**/ don't solve the problem, 

Low PTY issue.

Thanks, Matt

**Comment by worksofliam** [comment] 2022-04-21 02:16
Closing as this a dupe of #599.

**Closed** 2022-04-21 02:17 UTC
Labels: enhancement
