### ISSUE TITLE
Problem output doesn't read compilation errors

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#749] opened 2022-07-14 09:22 UTC
Hi,

I'm working in local, with a git repository outside IBM i (a local gitlab server).

With the intent of organize my source I create various folder, in every subfolder I create a qrpglesrc, qclsrc... 

Compiling that from this subfolder the problem output tab didn't read the compile output.

e.g.

I have  a repository for the utility:

utility
|-- httpclient
|   |-- qclsrc
|   |   |-- uhttpb04c.clle
|   |   `-- uhttpb05c.clle
|   |-- qcmdsrc
|   |   |-- uhttpbch.cmd
|   |   `-- uhttpbchi.cmd
|   |-- qfdssrc
|   |   `-- uhttpbch1f.sql
|   `-- qrpglesrc
|       |-- uhttpb03r.sqlrpgle
|       |-- uhttpb11r.sqlrpgle
|       |-- uhttpb12r.sqlrpgle
|       `-- uhttpbchi.sqlrpgle
|-- makefile
|-- powerha
|   |-- qclsrc
|   |   |-- setasp01c.clle
|   |   |-- startup.clle
|   |   |-- startupd1.clle
|   |   |-- startupd3.clle
|   |   |-- uchgnode0c.clle
|   |   |-- uchgnode1c.clle
|   |   |-- uchgpri01.clle
|   |   |-- ucrginfot.clle
|   |   `-- upwrdwn0c.clle
|   |-- qcmdsrc
|   |   `-- ucrginfo.cmd
|   |-- qfdssrc
|   |   `-- crgswc0f.sql
|   `-- qrpglesrc
|       |-- startupifc.sqlrpgle
|       |-- ucrgexit01.sqlrpgle
|       `-- ucrginfo.sqlrpgle
|-- qclsrc
|   |-- ccgrxmarc.clle
|   |-- utcrusr1c.clle
|   `-- utsndlog.clle
|-- qddssrc
|   `-- mbrmaifm.dspf
|-- qrpglesrc
|   |-- fixlogcsv.sqlrpgle
|   |-- mbrmainr.rpgle
|   |-- ugetcan1r.sqlrpgle
|   |-- ugetcan1t.sqlrpgle
|   |-- ujwtsrv.rpgle
|   |-- umipabadd.sqlrpgle
|   |-- utftpcr.sqlrpgle
|   |-- utjoblck.rpgle
|   |-- utnoti1r.sqlrpgle
|   |-- utnoti3r.sqlrpgle
|   |-- utsms.sqlrpgle
|   `-- utsmschg1.rpgle
|-- readme.md
`-- rsync
    |-- qclsrc
    |   `-- rsynccrt.clle
    |-- qfdssrc
    |   `-- rsync_tables.sql
    |-- qrpglesrc
    |   |-- rsync01r.sqlrpgle
    |   |-- rsync02r.sqlrpgle
    |   |-- rsync03r.sqlrpgle
    |   `-- rsync04r.sqlrpgle
    `-- sql
        `-- RSync_Setup_value.sql

If I compile the programs from httpclient subfolder I didn't see problem output.

Many thanks

**Comment by pabloto** [comment] 2022-07-14 11:48
If I didn't have  subfolder but directly qrpglesrc it works.

**Comment by worksofliam** [comment] 2022-07-14 12:33
@pabloto The issue is the fact that your command string is missing `*EVENTF`.

```
/QOpenSys/pkgs/bin/gmake srcdir=./lmax lmx015.rpgle
```

And later it prints:

```
*EVENTF not found in command string. Not fetching jdet/lmx015.
```

You should try something like this in your command:

```
/QOpenSys/pkgs/bin/gmake srcdir=./lmax options=*EVENTF lmx015.rpgle
```

This will set `options` to `*EVENTF`, which will likely do nothing other than tell Code for IBM i to fetch the errors.

**Comment by worksofliam** [comment] 2022-07-14 13:48
@pabloto so glad to hear it works! I will close this now, but please feel free to ask more questions.

**Closed** 2022-07-14 14:01 UTC
