### ISSUE TITLE
*.SQL unexpected error

### ISSUE THREAD

**Issue by JDubb-At-Nelnet** [halcyon-tech/vscode-ibmi#799] opened 2022-08-08 15:48 UTC
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
When executing an SQL statement in a *.SQL file, if I add 'fetch first 10 rows only' at the end of the statement, the error returned is 

"Keyword LIMIT not expected. Valid tokens: FOR USE SKIP WAIT WITH OPTIMIZE. (42601)"

If I create a *.INB file and put the same code inside an SQL cell, the code runs without issue.

**To Reproduce**
1. Create a *.SQL member in the object browser
2. Put in some SQL code that looks like this:
`Select * from somelib.sometable fetch first 10 rows only`
4. Execute the statement
5. Error 42601 is reported

**Expected behavior**
10 rows of results should be displayed in the output.

**Screenshots**
Screenshot showing the error:
![image](https://user-images.githubusercontent.com/107700100/183458447-74ae149b-396f-42ec-a39c-1ac43dc662bb.png)
Screenshot showing notebook doesn't get the error:
![image](https://user-images.githubusercontent.com/107700100/183458838-9ed017de-958d-4a54-82ec-de28d9b89054.png)

**Environment (please complete the following information):**
 - Extension version 1.5.3
 - IBM i OS version 7.4

**Additional context**

**Comment by worksofliam** [comment] 2022-08-08 15:51
I will fix this later today. The issue is related to how scrolling is turned on.

**Comment by worksofliam** [comment] 2022-08-09 14:06
Fixed. Out soon.

<img width="1514" alt="image" src="https://user-images.githubusercontent.com/3708366/183670077-60341203-d0cb-4173-9752-207fb418ae34.png">

**Comment by worksofliam** [comment] 2022-08-09 14:26
@JDubb-At-Nelnet It's been released in a new update. Give it a go and please re-open if you have further issues.

**Closed by worksofliam** 2022-08-09 14:26 UTC
Labels: bug, due-release
