### ISSUE TITLE
Errors not correctly cross-referenced to source (`*LVL2`)

### ISSUE THREAD

**Issue by fathert** [halcyon-tech/vscode-ibmi#405] opened 2021-11-19 12:07 UTC
**Issue**
When compiling an SQLRPGLE module with several levels of nested includes, error messages aren't correctly cross referenced to the source.

![image](https://user-images.githubusercontent.com/8808151/142617462-65e029f3-7295-4bfe-b1ba-400679b2ebe2.png)

**To Reproduce**
1) Create an SQLRPGLE source module with at least two levels of /include files and a deliberate syntax error.
2) Compile the module with the following command CRTSQLRPGI OBJ(&LIB/&OBJ) SRCFILE(&FILE/QRPGLESRC) CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT) OBJTYPE(*MODULE) RPGPPOPT(*LVL2)

**Expected behavior**
The red squiggle should appear underneath the syntax error and clicking on the error in the problem list should locate to the error line. However, the error squiggle appears at the end of the source file and this is where the cursor is repositioned when clicking the error in the problem log.

**Screenshots**
![image](https://user-images.githubusercontent.com/8808151/142618357-56689a13-03f1-4dea-b079-7eec2e65f7a9.png)

versus RDi

![image](https://user-images.githubusercontent.com/8808151/142618406-35262319-3d6c-4a4e-a9df-3a404acf5fab.png)

**Environment**
 - Extension version 0.8.2
 - IBM i OS version 7.2

**Additional context**
[vscode.sqlrpgle.txt](https://github.com/halcyon-tech/vscode-ibmi/files/7570082/vscode.sqlrpgle.txt)
[vscodeinc2.sqlrpgle.txt](https://github.com/halcyon-tech/vscode-ibmi/files/7570083/vscodeinc2.sqlrpgle.txt)
[vscodeinc.sqlrpgle.txt](https://github.com/halcyon-tech/vscode-ibmi/files/7570084/vscodeinc.sqlrpgle.txt)

**Comment by worksofliam** [comment] 2021-11-19 13:38
I've created the issue. If you take of *LVL2 then it works as expected.. but I am looking into this now.

**Comment by worksofliam** [comment] 2021-11-19 13:42
EVFEVENT content. We can see here, that because *LVL2 is being used, it's creating a temporary member with all the include statements expanded. Then is compiling that temporary member, and therefore the errors appear as if they're from one file.

```
TIMESTAMP  0 20211119083209
PROCESSOR  0 999 1
FILEID     0 999 000000 021 QTEMP/QSQLPRE(VSCODE) 20211119083209 0
FILEID     0 001 000000 023 BARRY/QRPGLESRC(VSCODE) 20211119083103 0
FILEID     0 002 000008 026 BARRY/QRPGLESRC(VSCODEINC) 20211119082637 0
EXPANSION  0 000 000000 000000 999 000009 000009
EXPANSION  0 002 000003 000003 999 000000 000000
FILEID     0 003 000007 027 BARRY/QRPGLESRC(VSCODEINC2) 20211119082613 0
EXPANSION  0 000 000000 000000 999 000016 000016
EXPANSION  0 003 000003 000003 999 000000 000000
FILEEND    0 003 000012
FILEEND    0 002 000010
FILEEND    0 001 000025
FILEEND    0 999 000047
PROCESSOR  0 999 1
FILEID     0 999 000000 023 QTEMP/QSQLTEMP1(VSCODE) 20211119083209 0
FILEID     0 001 000000 021 QTEMP/QSQLPRE(VSCODE) 20211119083209 0
EXPANSION  0 001 000000 000000 999 000035 000099
EXPANSION  0 001 000041 000041 999 000106 000114
EXPANSION  0 001 000041 000041 999 000116 000123
FILEEND    0 001 000047
FILEEND    0 999 000129
PROCESSOR  0 000 1
FILEID     0 001 000000 024 BARRY/EVFTEMPF01(VSCODE) 20211119083209 1
ERROR      0 001 1 000109 000109 009 000109 017 RNF7031 I 00 050 The name or indicator SQL_00001 is not referenced.
ERROR      0 001 1 000110 000110 009 000110 017 RNF7031 I 00 050 The name or indicator SQL_00002 is not referenced.
ERROR      0 001 1 000112 000112 009 000112 017 RNF7031 I 00 050 The name or indicator SQL_00004 is not referenced.
ERROR      0 001 1 000023 000023 003 000023 008 RNF7031 I 00 047 The name or indicator FIE1D1 is not referenced.
ERROR      0 001 1 000024 000024 003 000024 008 RNF7031 I 00 047 The name or indicator FIE1D2 is not referenced.
ERROR      0 001 1 000025 000025 003 000025 008 RNF7031 I 00 047 The name or indicator FIE1D3 is not referenced.
ERROR      0 001 1 000026 000026 003 000026 008 RNF7031 I 00 047 The name or indicator FIE1D4 is not referenced.
ERROR      0 001 1 000022 000022 008 000022 013 RNF7031 I 00 047 The name or indicator MYDS_T is not referenced.
ERROR      0 001 1 000099 000099 014 000099 019 RNF7031 I 00 047 The name or indicator SQFAPP is not referenced.
ERROR      0 001 1 000097 000097 014 000097 019 RNF7031 I 00 047 The name or indicator SQFCRT is not referenced.
ERROR      0 001 1 000098 000098 014 000098 019 RNF7031 I 00 047 The name or indicator SQFOVR is not referenced.
ERROR      0 001 1 000096 000096 014 000096 018 RNF7031 I 00 046 The name or indicator SQFRD is not referenced.
ERROR      0 001 1 000039 000039 011 000039 016 RNF7031 I 00 047 The name or indicator SQLAID is not referenced.
ERROR      0 001 1 000041 000041 011 000041 016 RNF7031 I 00 047 The name or indicator SQLABC is not referenced.
ERROR      0 001 1 000043 000043 011 000043 016 RNF7031 I 00 047 The name or indicator SQLCOD is not referenced.
ERROR      0 001 1 000045 000045 011 000045 016 RNF7031 I 00 047 The name or indicator SQLERL is not referenced.
ERROR      0 001 1 000047 000047 011 000047 016 RNF7031 I 00 047 The name or indicator SQLERM is not referenced.
ERROR      0 001 1 000049 000049 011 000049 016 RNF7031 I 00 047 The name or indicator SQLERP is not referenced.
ERROR      0 001 1 000051 000051 011 000051 016 RNF7031 I 00 047 The name or indicator SQLER1 is not referenced.
ERROR      0 001 1 000052 000052 011 000052 016 RNF7031 I 00 047 The name or indicator SQLER2 is not referenced.
ERROR      0 001 1 000053 000053 011 000053 016 RNF7031 I 00 047 The name or indicator SQLER3 is not referenced.
ERROR      0 001 1 000054 000054 011 000054 016 RNF7031 I 00 047 The name or indicator SQLER4 is not referenced.
ERROR      0 001 1 000055 000055 011 000055 016 RNF7031 I 00 047 The name or indicator SQLER5 is not referenced.
ERROR      0 001 1 000057 000057 011 000057 017 RNF7031 I 00 048 The name or indicator SQLERRD is not referenced.
ERROR      0 001 1 000059 000059 011 000059 016 RNF7031 I 00 047 The name or indicator SQLWN0 is not referenced.
ERROR      0 001 1 000060 000060 011 000060 016 RNF7031 I 00 047 The name or indicator SQLWN1 is not referenced.
ERROR      0 001 1 000061 000061 011 000061 016 RNF7031 I 00 047 The name or indicator SQLWN2 is not referenced.
ERROR      0 001 1 000062 000062 011 000062 016 RNF7031 I 00 047 The name or indicator SQLWN3 is not referenced.
ERROR      0 001 1 000063 000063 011 000063 016 RNF7031 I 00 047 The name or indicator SQLWN4 is not referenced.
ERROR      0 001 1 000064 000064 011 000064 016 RNF7031 I 00 047 The name or indicator SQLWN5 is not referenced.
ERROR      0 001 1 000065 000065 011 000065 016 RNF7031 I 00 047 The name or indicator SQLWN6 is not referenced.
ERROR      0 001 1 000066 000066 011 000066 016 RNF7031 I 00 047 The name or indicator SQLWN7 is not referenced.
ERROR      0 001 1 000067 000067 011 000067 016 RNF7031 I 00 047 The name or indicator SQLWN8 is not referenced.
ERROR      0 001 1 000068 000068 011 000068 016 RNF7031 I 00 047 The name or indicator SQLWN9 is not referenced.
ERROR      0 001 1 000069 000069 011 000069 016 RNF7031 I 00 047 The name or indicator SQLWNA is not referenced.
ERROR      0 001 1 000070 000070 011 000070 017 RNF7031 I 00 048 The name or indicator SQLWARN is not referenced.
ERROR      0 001 1 000072 000072 011 000072 016 RNF7031 I 00 047 The name or indicator SQLSTT is not referenced.
ERROR      0 001 1 000083 000083 015 000083 026 RNF7031 I 00 051 The name or indicator SQLCLSE... is not referenced.
ERROR      0 001 1 000087 000087 015 000087 026 RNF7031 I 00 051 The name or indicator SQLCMIT... is not referenced.
ERROR      0 001 1 000079 000079 015 000079 026 RNF7031 I 00 051 The name or indicator SQLOPEN... is not referenced.
ERROR      0 001 1 000125 000125 006 000125 009 RNF7030 S 30 042 The name or indicator TEST is not defined.
ERROR      0 001 1 000029 000029 008 000029 013 RNF7031 I 00 047 The name or indicator VSCODE is not referenced.
ERROR      0 001 1 000125 000125 006 000125 009 RNF7503 S 30 051 Expression contains an operand that is not defined.
ERROR      0 001 0 000000 000000 000 000000 000 RNS9308 T 50 057 Compilation stopped. Severity 30 errors found in program.
FILEEND    0 001 000129
```

**Comment by fathert** [comment] 2021-11-19 13:44
I think that might be because the the nested includes aren't included. As there are no dependencies on anything in the includes in my example, they're just there to create a minimum viable example, then that's probably why it compiles without the *LVL2 option. If you modded the example to use something from the VSCODEINC2 file then I daresay it wouldn't compile without *LVL2.

**Comment by worksofliam** [comment] 2021-11-19 13:52
Adding a reference to `myds_t` from VSCODEINC2 was still displaying correct errors without LVL2:

![image](https://user-images.githubusercontent.com/3708366/142633513-ec1fe700-5194-4838-b21e-cc8bb0d647c8.png)

Is this what you were referring to?

**Comment by fathert** [comment] 2021-11-19 15:08
You need the make the SQL code dependent on the nested include, so something like this:

**VSCODEINC2**
```
**FREE
/if defined (VSCODE2)
/eof
/endif
/define VSCODE2

dcl-ds myDs_t qualified template;
  count int(10);
end-ds;
```

**VSCODE**
```
**FREE
ctl-opt copyright('')
  datfmt(*ISO) datedit(*YMD/) timfmt(*ISO)
  debug(*YES) option(*NODEBUGIO: *SRCSTMT)

  main(main);

/include qrpglesrc,VSCODEINC

//**************************************************************************************************
// Entry point
//**************************************************************************************************
dcl-proc main;
  dcl-pi *N;
  end-pi;

  dcl-ds myDs likeds(myDs_t);

  exec sql
    select count(*) into :myDs from QSYS2.SYSTABLES;

//  if test = *ON;
//  endif;

end-proc;
//**************************************************************************************************
```

**Comment by worksofliam** [comment] 2021-11-19 15:11
@fathert Got you. 

Thanks for raising it. I am gonna spend some of my weekend working on it. Got a busy day today but will get my head down into it ASAP.

**Comment by fathert** [comment] 2021-11-19 15:16
Great, thanks for looking at it and for your hard work getting it to work at all! I'm looking forward to being able to use VS Code as my daily editor 😄

**Comment by worksofliam** [comment] 2021-11-19 15:35
I have recreated the issue in this JSFiddle in case anyone else wants to have a go at the issue.

Specifically, it's the `getErrors` function that needs work.

https://jsfiddle.net/4fa9je1o/1/

**Comment by fathert** [comment] 2021-11-23 17:25
Oh that's great, I meant to have a look over the weekend, but never got the time. Thanks very much, I look forward to trying it!

**Comment by edmundreinhardt** [comment] 2021-11-23 18:07
@worksofliam Hi Liam, here is the official documentation of the EVFEVENT file format.  So sorry it took me this long to find it.
https://www.ibm.com/docs/en/rdfi/9.6.0?topic=reference-events-file-format

**Comment by edmundreinhardt** [comment] 2021-11-23 18:07
Hopefully this will tell you that you did it all right :-)

**Comment by worksofliam** [comment] 2021-11-23 23:22
Thought I'd share an update as my day comes to an end and I have a beer to dwell.

This fix is surprisingly tedious. I got a bunch of code done and got it working as expected with the code sample provided by @fathert. Then I tried with other code bases and not having much luck. There is a lot of edge cases to test and it's going to be a little bit before it's released.

I suspect I'll share the branch tomorrow.

**Comment by fathert** [comment] 2021-11-24 09:54
We have a lot of SQLRPGLE code with lots of deep nesting, I'm happy to beta test something if that would help?

**Comment by worksofliam** [comment] 2021-11-24 13:54
@fathert Funnily enough, it seems to work perfectly when there is deep nesting. Otherwise, it's one or two lines off... will have to keep working on this tonight and over the weekend. 

Will keep you posted.

**Comment by worksofliam** [comment] 2021-11-25 16:58
I have been working on this for days, and I’m getting very close, but I’m working out the kinks for the expansion keyword. Turns out, it doesn’t just expand, it can also delete lines. I didn’t know that until yesterday. Awfully stressful.

I had to take a break yesterday and today because I was just getting frustrated. I will continue tomorrow sometime and post another update.

**Comment by worksofliam** [comment] 2021-11-29 17:12
Monday update: I got it working over the weekend. I hate the way the source maps are implemented for the compilers.

There will be a release tonight, and you must enable this fix since I don't want to disturb existing situations. When everyone is happy with the fix, then it will be released as the default.

Liam

**Comment by worksofliam** [comment] 2021-11-29 22:14
@fathert

The fix preview is out in 0.8.3. Open the VS Code settings, search for `error parser`, enable it, and then compile away.

![image](https://user-images.githubusercontent.com/3708366/143951129-c2e63707-4fb9-4695-99ba-a15bc369b02d.png)

**Comment by worksofliam** [comment] 2021-11-29 22:18
Please, of course, post any feedback here.

**Comment by fathert** [comment] 2021-12-01 15:02
So far, so good Liam, I'll keep using it over the next few days and let you know how it goes.

**Comment by cbuck0222** [comment] 2021-12-01 15:26
So did we determine that this fixed for RPGPPOPT(*LVL2) or does it need to be RPGPPOPT(*NONE)? After enabling the fix, I just tried with *LVL2 and encountered the same issue on a source today. Switched it to *NONE to get it to reference the appropriate line, but I know that was causing some other issues in certain scenarios.

**Comment by worksofliam** [comment] 2021-12-01 16:18
@cbuck0222 I cleaned it up for you.

This should be enough to work with, and from a glance, I can see it's likely due to the copybook at the end.

Would you mind also sharing this info:

* Do you have the new parser enabled?
* Could you please share a screenshot of where the errors are appearing in your editor

**Comment by cbuck0222** [comment] 2021-12-01 16:22
@worksofliam thanks. For future reference, could you tell me what you did to make sure the correct lines got formatted as "code"?

And yes, I have the new parser enabled:
![image](https://user-images.githubusercontent.com/86483883/144271947-6ba02941-bdee-4504-a695-fe0cd51f47df.png)

For an easy one, the error is that my record format dsact1 is spelled incorrectly, "dscat1". It's referencing line 134 though. Should be on 176 in the editor. 
![image](https://user-images.githubusercontent.com/86483883/144272206-9445443b-9d27-4ac8-865b-3ffe4ecfbf22.png)

**Comment by worksofliam** [comment] 2021-12-01 16:46
@cbuck0222 

You can use three backticks. See example here: https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by cbuck0222** [comment] 2021-12-01 16:54
@worksofliam 
CRTSQLRPGI OBJ(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) INCFILE(*LIBL/*SRCFILE) RPGPPOPT(*LVL2) TGTRLS(V7R4M0) REPLACE(*YES) SQLCURRULE(*DB2) DBGVIEW(*SOURCE)

**Comment by worksofliam** [comment] 2021-12-01 16:57
@cbuck0222 Thanks! I see that if I take `*LVL2` off, it shows the errors as expected correct - which is good. Investigating the level two stuff later this evening.

**Comment by cbuck0222** [comment] 2021-12-01 17:07
Yep, just tried compiling with moving the copybook to the top of my subprocedures and tit worked with *LVL2.

**Comment by worksofliam** [comment] 2021-12-01 21:19
I thought I had it working, but wow this is a surprisingly complicated edge case. Might be another few hours.

**Comment by worksofliam** [comment] 2021-12-02 04:27
Okay, 6 hours later: mostly spent debugging. Awfully stressful. I even have a new branch with a complete re-write (the third). No progress. Sad times.

**Comment by cbuck0222** [comment] 2021-12-02 13:18
Sorry to hear. At least now knowing a copy book can't be the last line of your code, I can avoid for now. Hopefully, that's the only case where this remains an issue.

**Comment by cwbuck** [comment] 2021-12-03 15:58
Had a profile issue -- I was previously @cbuck0222. 
Wanted to share that I even after moving the copy book up from the very bottom of the program, I have run into line reference issues again for errors occurring on any line ABOVE the copy book sample I sent. Interestingly enough, any errors occurring on lines BELOW the copy book appear to reference correctly. So it does not appear to just be that the copy book cannot be the last line of your code. You may already have concluded this, but let me know if you'd like another example. @worksofliam

**Comment by worksofliam** [comment] 2021-12-03 16:08
@cwbuck Feel free to share the file you changed to create that issue.

I'll be honest with you, this is a rather large issue and requires a bunch of hours to get it done. It should be a simple fix, but there are no details online on how the EVFEVENT file should be interpreted.. it's purely a debugging game from this point. I am glad this is just an issue with *LVL2 for now.

**Comment by cwbuck** [comment] 2021-12-03 16:14
I understand. It's probably not 

I've just slightly modified the same program as earlier. It's giving me an error on my btnUpdate indicator no longer being defined (removed from my DDS). Since I didn't provide the DDS, you can probably reproduce fairly easily. Attempts to reference 92 when it should be 134.

![image](https://user-images.githubusercontent.com/68613130/144635524-49b3d98f-5735-423e-957f-6f716b79459f.png)



**QRPGLESRC/VRR3000**

```
**free
//==============================================================================
// C O M P I L E R  O P T I O N S
//==============================================================================

ctl-opt
  dftactgrp(*NO)
  option(*nodebugio:*srcstmt)
  extbinint(*yes);


//==============================================================================
// F I L E  D E F I N I T I O N S
//==============================================================================

// 21st UI Header and Background
dcl-f SYD8500D workstn
  extFile(*EXTDESC) extDesc('SYD8500D')
  handler('PROFOUNDUI(HANDLER)');

// Variable Rate Index Queue
dcl-f VRD3000 workstn extDesc('VRD3000')
  usage(*INPUT:*OUTPUT)
  sfile(dsasf1:sfrra1)
  handler('PROFOUNDUI(HANDLER)');


//==============================================================================
// E X T E R N A L  P R O C E D U R E S
//==============================================================================

// UI Message Pop-up
/include qcpylesrc,syr8501_pr


//==============================================================================
// D A T A  S T R U C T U R E S
//==============================================================================

// Program status data structure
/include qcpylesrc,gcpyr004

dcl-ds
  cursorStatus qualified inz;
    isOpen             ind       inz(false);
    state              char(5);
    class              char(2)   overlay(state);
end-ds;

//==============================================================================
// G L O B A L  V A R I A B L E S
//==============================================================================

// Program flow
dcl-s endProgram      ind inz(*off);
dcl-s sfrra1          int(5);

//==============================================================================
// G L O B A L  C O N S T A N T S
//==============================================================================

dcl-c true             '1';
dcl-c false            '0';
dcl-c pass             '1';
dcl-c fail             '0';
dcl-c clicked          '1';

// subfile options
dcl-c viewRate         'View';
dcl-c updateRate       'Update Rate';

// display screens
dcl-c mainScreen       'DSACT1';
dcl-c viewRateScreen   'DSBCT1';
dcl-c updateRateScreen 'DSCCT1';

// constants for SQLSTATE class values
dcl-c stmtOk           '00';
dcl-c stmtWarning      '01';
dcl-c stmtError        '02';

// Setup SQL Environment
exec SQL
  set option commit    = *none
           , dlyprp    = *no
           , cloSQLCsr = *endmod
           , datFmt    = *iso
           , naming    = *sys;


//==============================================================================
// M A I N
//==============================================================================

initialization();
dow not endProgram;

  // RATE INDEX QUEUE SCREEN (MAIN)
  //================================
  show_screen(mainScreen);

  // Process user actions on screen
  select;

    // 'Exit' button
    //---------------
    when btnExit = clicked;
      endProgram = true;

    // 'See Confirmed Today' button
    //------------------------------
    when btnSeeConf = clicked;
      // do this

    // Action selected for a row in grid
    //-----------------------------------
    when selectRow = clicked;

      // VIEW/UPDATE RATE DETAIL SCREENS
      //=================================
      if rowOption = viewRate;
        show_screen(viewRateScreen);
      elseif rowOption = updateRate;
        show_screen(updateRateScreen);
      endif;

      // Process user actions on screen
      select;

        // 'Update' button
        //-----------------
        when btnUpdate = clicked;
          // do some stuff here

        // 'Exit' button
        //---------------
        when btnExit = clicked;
          endProgram = true;

        // 'Back' button
        //---------------
        when btnBack = clicked;
          iter;


      endsl;

  endsl;

enddo;

//------------------------------------------------------------------------------
// Exit program
//------------------------------------------------------------------------------

*inlr = *on;
return;


//==============================================================================
// S U B P R O C E D U R E S
//==============================================================================
//=======================================================================
// Procedure name: SQLError
// Purpose:        Monitor for SQL Errors.
//                 Displays Popup notification if SQL error
//                 occurs.
// Returns:        SQLError=True(1)/False(0)
// Example:
//                 If not SqlError(' on Object Update');
//=======================================================================
/include qcpylesrc,syr8502_c


//------------------------------------------------------------------------------
//   Procedure: initialization
// Description: Intializes program
//------------------------------------------------------------------------------

dcl-proc initialization;

  // Set Heading informational values
  wdwTitle   = 'Servicing';
  wdwPnlDesc = 'Rate Index Queue';
  wdwUser    = psdsCurrUser;

  // Set Default Button panel height and width
  btnPnlHgt  = 720;
  btnPnlWdth = 160;

  // Set Default Content panel height and width
  cntPnlHgt  = 720;
  cntPnlWdth = 1100;
  wdwTtlWdth = cntPnlWdth; // Window title width

  // Set Default Window Title LEFT starting position
  wdwTtlLeft = 160;
  // Set Default Window Info(display,user) LEFT starting positions
  wdwInfLeft = 1118;

  showLogo = true;  // Show Logo

end-proc;


//------------------------------------------------------------------------------
//   Procedure: show_screen
// Description: Displays the desired record format
//------------------------------------------------------------------------------

dcl-proc show_screen;
  dcl-pi *n;
    recordFormat   char(10) const;
  end-pi;

  // Configure display format information
  wdwPgmFmt = %trimr(psdsProgName) +':'+ recordFormat;

  // Write 21st UI background & header
  write window;

  // Determine which record format to display
  select;
    when recordFormat = 'DSACT1';
      clear_indexSubfile();
      load_indexSubfile();
      exfmt dsact1;
    when recordFormat = 'DSBCT1';
      exfmt dsbct1;
    when recordFormat = 'DSCCT1';
      exfmt dscct1;
  endsl;

end-proc;


//------------------------------------------------------------------------------
//   Procedure: clear_indexSubfile
// Description: Clears the rate index queue subfile
//------------------------------------------------------------------------------

dcl-proc clear_indexSubfile;

  clear sfrra1;
  clear sfrna1;
  sfclr1 = *on;
  write dsact1;
  sfclr1 = *off;

end-proc;

//------------------------------------------------------------------------------
//   Procedure: load_indexSubfile
// Description: Loads the rate index queue subfile with records from...
//------------------------------------------------------------------------------

dcl-proc load_indexSubfile;

  // Declare cursor
  exec sql
    declare ratesQueueCursor cursor for
    select GNS8301(VRTRDATE), VINIFREQ, VRTINDEX, VINIDESC
      from VRMVINDX
      join VRMVRATE on VININDEX = VRTINDEX;

  open_cursor();
  dow fetch_cursorRow();
    sfrra1 += 1;
    write dsasf1;
  enddo;
  close_cursor();

  if sfrna = 0 and sfrra > 0;
    sfrna = 1;
  endif;

end-proc;


//------------------------------------------------------------------------------
//   Procedure: open_cursor
// Description: Opens the cursor
//     Returns: success indicator  (true/false)
//------------------------------------------------------------------------------

dcl-proc open_cursor;
  dcl-pi *n ind end-pi;

  exec sql
    open ratesQueueCursor;
  sqlError(' on open rates queue cursor.');

  cursorStatus.state = sqlstate;
  cursorStatus.isOpen = (cursorStatus.class = stmtOK);

  return cursorStatus.isOpen;

end-proc;


//------------------------------------------------------------------------------
//   Procedure: close_cursor
// Description: Closes the cursor
//     Returns: success indicator  (true/false)
//------------------------------------------------------------------------------

dcl-proc close_cursor;
  dcl-pi *n ind end-pi;

  if cursorStatus.isOpen;
    exec sql
      close ratesQueueCursor;
    sqlError(' on close rates queue cursor.');

    cursorStatus.state = sqlstate;
    cursorStatus.isOpen = (cursorStatus.class = stmtOK);
  endIf;

  return (not cursorStatus.isOpen);

end-proc;


//------------------------------------------------------------------------------
//   Procedure: fetch_cursorRow
// Description: Gets next record from the cursor
//     Returns: success indicator  (true/false)
//------------------------------------------------------------------------------

dcl-proc fetch_cursorRow;
  dcl-pi *n ind end-pi;

    dcl-s status ind inz(fail);

  if cursorStatus.isOpen;
    exec sql
      fetch from ratesQueueCursor
      into :sfEffDate, :sfFreq, :sfIndex, :sfDesc;
    sqlError(' on fetch from rates queue cursor.');
    cursorStatus.state = sqlstate;
    status = (cursorStatus.class = stmtOK);
  endif;

  return status;

end-proc;

```

**Comment by SJLennon** [comment] 2022-04-25 18:36
@worksofliam Hate to have to report this, but the "Try New Error Parser" stops errors being found on a CLLE program.
Simple use case:
```

pgm
dcl &xxx *char 10
chgvar &yyy 'Fred'
ENDPGM

```
If I compile without "Try New Error Parser" unchecked, I get an error.

With "Try New Error Parser" checked I get no errors.

Compile command is:
CRTBNDCL PGM(LENNONS1/ZB) SRCFILE(LENNONS1/PRT) OPTION(*EVENTF) DBGVIEW(*SOURCE)

**Comment by worksofliam** [comment] 2022-04-25 18:40
@SJLennon Thanks for letting me know. I will have to look into this tonight!

**Comment by SJLennon** [comment] 2022-04-25 21:22
Not urgent for anything I'm doing.

**Comment by edmundreinhardt** [comment] 2023-08-02 12:58
Good news, this works with this new eventf parser at https://github.com/IBM/ibmi-eventf-parser
We plan to create a PR to use this external repo which has technology from IBM to do eventf parsing for Code for IBM i

**Closed** 2023-08-22 01:18 UTC
Labels: bug, due-release
