### ISSUE TITLE
IBM i Debug not working on Pop OS Linux distro

### ISSUE THREAD

**Issue by jwoehr** [halcyon-tech/vscode-ibmi#1058] opened 2023-02-11 23:21 UTC
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.
_Report an Issue gives "Github Query Limit Exceeded Please Wait"_

**Describe the bug**
IBM i Debug installed on VSCode 1.75.1 on Mac OS works for me
IBM  i Debug installed on VSCode 1.75.1 on Pop OS (Ubuntu-like distro) does not work for me.

**To Reproduce**
1. Load source from remote IBM i connection
2. Click on the **IBM i Debug: Start Debugging Active Source** widget (or enter same in the command palette)
3. Blank screen, no debug activity
4. Debug console shows packet sent and nothing more.
5. After running on Mac and going back to Pop OS the console goes farther and shows that traces have been generated (attached)

**Expected behavior**
The debug session to start.

**Environment (please complete the following information):**
 - Extension version IBM i Debug v1.0.0
 - IBM i OS version7.4
 - Linux pop-os 6.0.12-76060006-generic #202212290932~1674139725~22.04~ca93ccf SMP PREEMPT_DYNAMIC Thu J x86_64 x86_64 x86_64 GNU/Linux
 - NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Additional context**
[PDT_DAAS_20230211_180537_0233_7_DAP.txt](https://github.com/halcyon-tech/vscode-ibmi/files/10714918/PDT_DAAS_20230211_180537_0233_7_DAP.txt)
[PDT_DAAS_20230211_180537_0233_7_.zip](https://github.com/halcyon-tech/vscode-ibmi/files/10714919/PDT_DAAS_20230211_180537_0233_7_.zip)

**Comment by jwoehr** [comment] 2023-02-11 23:29
Weird. Now it is working. I can fully debug my program. Apparently running it from the Mac set something up that isn't getting set up from Pop OS.

**Comment by worksofliam** [comment] 2023-02-12 23:46
Closing as possible duplicate of #1059

**Closed by worksofliam** 2023-02-12 23:46 UTC
Labels: debug
