### ISSUE TITLE
QRPGLESRC

### ISSUE THREAD

**Issue by mattsheawave** [halcyon-tech/vscode-ibmi#532] opened 2022-02-10 21:24 UTC
I can see my source physical files in the libraries.  I can open source from all the other source physicals but QRPGLESRC.  I click or double click and nothing happens.  
Thoughts,
Matt

**Comment by worksofliam** [comment] 2022-02-10 21:36
@mattsheawave What if you disable SQL in the connection settings, reconnect, and try again?

**Comment by worksofliam** [comment] 2022-02-10 22:36
Did you get this error?

![image](https://user-images.githubusercontent.com/3708366/153508312-1f4b80a5-977c-4f85-96e3-24ddcb708904.png)

**Comment by paolos69** [comment] 2022-02-11 13:07
I have disabled SQL
gives me this error: "Source date support is disabled. SQL must be enabled."

**Comment by paolos69** [comment] 2022-02-11 13:08
I have disabled SQL,
gives me this error: "Source date support is disabled. SQL must be enabled."

**Comment by paolos69** [comment] 2022-02-11 13:09
I have disabled SQL
gives me this error: "Source date support is disabled. SQL must be enabled."

**Comment by paolos69** [comment] 2022-02-11 13:31
![image](https://user-images.githubusercontent.com/34394401/153600060-ab57e99b-b1f2-4d99-8404-1d2457458b77.png)

**Comment by worksofliam** [comment] 2022-02-11 13:43
For source dates to work, your QCCSID must not be 65535.

**Comment by paolos69** [comment] 2022-02-11 14:26
can i change it?

**Comment by paolos69** [comment] 2022-02-11 14:48
280?

**Comment by mattsheawave** [comment] 2022-02-11 16:05
Upon VS Code startup I receive a message "QCCSID is set to 65535. Disabling SQL Support."  So it appears, SQL is already disabled.
I can successfully edit CL and DDS source, just not RPGLE.

**Comment by worksofliam** [comment] 2022-02-11 16:40
@mattsheawave what is stopping you from editing RPGLE?

**Comment by mattsheawave** [comment] 2022-02-11 17:13
@worksofliam When I click on an RPGLE member, nothing happens.  It doesn't open in the editor window.  Single click, double click.  When I single click on CL or DDS members, they open fine in the editor window.

**Comment by worksofliam** [comment] 2022-02-11 17:28
@mattsheawave can you go to the Code for IBM i output tab and paste me the content after you try to open the member?

**Comment by worksofliam** [comment] 2022-02-11 18:20
@mattsheawave You have a different issue.

> Database file CCSID is 65535

This is because your source file is in CCSID 65535. You can override this by changing the 'source file CCSID' connection setting.

**Comment by worksofliam** [comment] 2022-02-12 16:06
@mattsheawave Source date support will be enable-able without SQL support as of tomorrow.

**Comment by worksofliam** [comment] 2022-02-12 16:10
Possible dupe of #534

**Closed** 2022-02-12 16:10 UTC
Labels: discussion
