### ISSUE TITLE
SSH connection in VS code terminal

### ISSUE THREAD

**Issue by GajenderI** [halcyon-tech/vscode-ibmi#413] opened 2021-12-01 06:19 UTC
**Is your feature request related to a problem? Please describe.**
Since I work a lot in PASE env and IBMi I always have to open a ssh connection apart from Code for I, 5250 session(not needed frequently).  

**Describe the solution you'd like**
It would be really handy if when I connect to a system using Code for I it connects a ssh session also in terminal using the same credentials. 

**Describe alternatives you've considered**
After connecting using extension I open up the terminal and do a ssh connection. 

**Additional context**
If opening of terminal with a ssh connection to the same system can be made possible then this will be a time saver specially when we reconnect after losing connection to the system.

**Comment by worksofliam** [comment] 2021-12-01 13:13
Possible duplicate of #289. #412 will implement this.

**Closed** 2021-12-01 13:14 UTC
Labels: idea

**Comment by GajenderI** [comment] 2021-12-09 17:05
Not a duplicate of #289  because what i request is to have a terminal with ssh connection when we connect to an IBMi using code for i. #289 wants a 5250 session but i want just an SSH connection.

**Comment by worksofliam** [comment] 2021-12-09 17:07
@GajenderI 

#412 Implemented this :) 

You can now click on Terminals and select PASE 😄
